CH_FIELD_MAPPING = {
    'Object ID': 'listing_id',
    'listing_url': 'listing_url',
    'Price': 'price',
    'Price per sqm': 'price_per_sqm',
    'Mortgage Rate': 'mortgage_rate',
    'Address': 'address',
    'Address ID': 'address_id',
    'Area': 'area',
    'Rooms': 'rooms',
    'Floor': 'floor',
    'Description': 'description',
    'Published Date': 'published_date',
    'Updated Date': 'updated_date',
    'Seller ID': 'seller_id',
    'Seller Name Hash': 'seller_name_hash',
    'Company Name': 'company_name',
    'Company ID': 'company_id',
    'Property Type': 'property_type',
    'Category': 'category',
    'House Floors': 'house_floors',
    'Deal Type': 'deal_type',
    'Discount Status': 'discount_status',
    'Discount Value': 'discount_value',
    'Placement Paid': 'placement_paid',
    'Big Card': 'big_card',
    'Pin Color': 'pin_color',
    'Longitude': 'longitude',
    'Latitude': 'latitude',
    'Subway Distances': 'subway_distances',
    'Subway Names': 'subway_names',
    'Photos URLs': 'photo_urls',
    'Monthly Payment': 'monthly_payment',
    'Advance Payment': 'advance_payment',
    'Auction Status': 'auction_status',
    'uid': 'uid',
    'platform_id': 'platform_id',
    'created_at': 'created_at',
    'seller_type': 'seller_type',
    'flat_type': 'flat_type',
    'height': 'height',
    'area_rooms': 'area_rooms',
    'previous_price': 'previous_price',
    'renovation_offer': 'renovation_offer',
    'balcony_type': 'balcony_type',
    'window_view': 'window_view',
    'built_year_offer': 'built_year_offer',
    'building_state': 'building_state',
    'type_house_offer': 'type_house_offer',
    'valid': 'valid',
    'subway_time': 'subway_time',
}
